---

- name: Add Atom repo
  yum_repository:
    name: atom
    description: Atom Editor
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    gpgcheck: yes

- name: display contents of repo files
  debug: var=item
  with_file:
    - "/etc/yum.repos.d/atom.repo"
