---
# Installs and configures DNF repositories

  # Requried for SE-Linux
- name: install the latest version of libselinux-python
  dnf:
    name: libselinux-python
    state: latest

- name: Get Optional Packages from group packages
  lineinfile:
    path: /etc/yum.conf
    create: yes
    state: present
    regexp: '^group_package_types='
    line: 'group_package_types=optional'

- name: Add Atom repo
  yum_repository:
    name: atom
    description: Atom Editor
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/$basearch
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    gpgcheck: no
    repo_gpgcheck: yes
    enabled: yes
    state: present

- name: Add Docker Stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes
    enabled: yes
    state: present

- name: Add Google Chrome repo
  yum_repository:
    name: google-chrome
    description: google-chrome - $basearch
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
    repo_gpgcheck: yes
    enabled: yes
    state: present

- name: Add Google Cloud SDK
  yum_repository:
    name: google-cloud-sdk
    description: Google Cloud SDK
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    repo_gpgcheck: yes
    enabled: yes
    state: present

- name: display contents of repo related files
  debug: var=item
  with_file:
    - "/etc/yum.conf"
    - "/etc/yum.repos.d/atom.repo"
    - "/etc/yum.repos.d/docker-ce.repo"
    - "/etc/yum.repos.d/google-chrome.repo"
    - "/etc/yum.repos.d/google-cloud-sdk.repo"
  ignore_errors: yes

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
