---

- name: Get Optional Packages from group packages
  lineinfile:
    path: /etc/yum.conf
    create: yes
    state: present
    regexp: '^group_package_types='
    line: 'group_package_types=optional'

### Broken - Does not work for some reason ###
#- name: Add Atom repo
#  yum_repository:
#    name: Atom
#    description: Atom Editor
#    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/\$basearch
#    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
#    gpgcheck: no
#    repo_gpgcheck: yes

- name: Add Atom repo gpgkey
  shell: rpm --import https://packagecloud.io/AtomEditor/atom/gpgkey
  args:
    warn: false

- name: Add Atom repo
  shell: sh -c 'echo -e "[Atom]\nname=Atom Editor\nbaseurl=https://packagecloud.io/AtomEditor/atom/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/AtomEditor/atom/gpgkey" > /etc/yum.repos.d/atom.repo'
  args:
    warn: false

- name: Install latest version of dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: latest

- name: Install Docker repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: false

- name: Install Google Chrome repo
  shell: sh -c 'echo -e "[google-chrome]\nname=google-chrome - \$basearch\nbaseurl=http://dl.google.com/linux/chrome/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://dl-ssl.google.com/linux/linux_signing_key.pub" > /etc/yum.repos.d/google-chrome.repo'
  args:
    warn: false

- name: display contents of repo related files
  debug: var=item
  with_file:
    - "/etc/yum.conf"
    - "/etc/yum.repos.d/atom.repo"
    - "/etc/yum.repos.d/docker-ce.repo"
    - "/etc/yum.repos.d/google-chrome.repo"
  ignore_errors: yes

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
