---

- name: Add Atom repo
  yum_repository:
    name: Atom
    description: Atom Editor
    baseurl: https://packagecloud.io/AtomEditor/atom/el/7/
    gpgkey: https://packagecloud.io/AtomEditor/atom/gpgkey
    gpgcheck: yes
