---
# Installs text Editors

- name: install the 'Editors' package group
  dnf:
    name: '@Editors'
    state: present

- name: install the latest version of atom
  dnf:
    name: atom
    state: latest
  register: atom_result
  ignore_errors: yes

- name: atom installation status
  debug:
    var: atom_result

- name: install the latest version of texstudio
  dnf:
    name: texstudio
    state: latest
