---
# Installs text Editors

- name: install the 'Editors' package group
  dnf:
    name: '@Editors'
    state: present

- name: install the latest version of atom
  dnf:
    name: atom
    state: latest

sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda x:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main('/opt')"

- name: install the latest\-ish version of calibre
  dnf:
    name: calibre
    state: latest

- name: install the latest version of texstudio
  dnf:
    name: texstudio
    state: latest
