---
# Installs cloud management tools

- name: install the 'Cloud Management Tools' package group
  dnf:
    name: '@Cloud Management Tools'
    state: present

- name: install the 'Vagrant with libvirt support' package group
  dnf:
    name: '@Vagrant with libvirt support'
    state: present

- name: install the latest version of Ansible
  dnf:
    name: ansible
    state: latest

- name: install the latest version of google-cloud-sdk
  dnf:
    name: google-cloud-sdk
    state: latest

- name: download and install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_ver }}/terraform_{{ terraform_ver }}_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0775
    remote_src: yes
