---
- name: Provision Laptop
  hosts: local
  become: yes
  strategy: debug

  roles:
    - { role: init, become: yes }
    - { role: libs, become: yes }
    - { role: tools, become: yes }
    - { role: git, become: yes }
    - { role: editors, become: yes }
    - { role: gcloud, become: yes }
    - { role: docker, become: yes }
    - { role: packer, become: yes }
    - { role: vagrant, become: yes }
    - { role: finalize, become: yes }
