---
- name: Provision Laptop
  hosts: local
  become: yes
  strategy: debug

  roles:

    - role: init
      become: yes
      tags: init

    - role: libs
      become: yes
      tags: libs

    - role: tools
      become: yes
      tags: tools

    - role: git 
      become: yes
      tags: git

    - role: editors
      become: yes
      tags: editors
    
    - role: tex
      become: yes
      tags: tex
      
    - role: gcloud
      become: yes
      tags: gcloud

    - role: docker
      become: yes
      tags: docker

    - role: packer
      become: yes
      tags: packer

    - role: vagrant 
      become: yes
      tags: vagrant

    - role: vault
      become: yes
      tags: vault

    - role: nvidia
      become: yes
      tags: nvidia

    - role: finalize
      become: yes
      tags: finalize
