---
# Tasks to create local user
# Source: https://lebenplusplus.de/2017/04/19/creating-users-and-their-passwords-with-ansible/

- name: create {{ user }}
  user:
    name: "{{ user }}"
    shell: /bin/zsh
    groups: wheel

- name: Unlock password for {{ user }} and set it to empty
  command: passwd -d {{ user }}

- name: Expire password
  command: chage -d 0 {{ user }}
