---
- name: install the rpmfusion repo packages
  dnf: name={{ item }}
       state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_ver }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_ver }}.noarch.rpm

- name: Install Broadcom Wifi Driver
  dnf:
    name: broadcom-wl
    state: latest

- name: Rebuild the kernel extension in broadcom driver package
  shell: akmods
  

