---
  # Install Docker

- name: Add Docker Stable repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
    gpgkey: https://download.docker.com/linux/fedora/gpg
    gpgcheck: yes
    enabled: yes
    state: present

- name: install the latest stable version of docker-ce
  dnf:
    name: docker-ce
    state: latest

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true

- name: Add {{ docker_user }} user to docker group
  user:
    name: '{{ docker_user }}'
    groups: docker
    append: yes

# Needs a static IPv6 prefix
# - name: Enable IPv6
#   copy:
#     src: files/daemon.json
#     dest: /etc/docker/daemon.json

- name: Download and install Docker Compose {{ docker_compose_ver }}
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/docker-compose'
    mode: 0755
