---
# Installs containerization Tools

- name: install the latest version of kubectl
  dnf:
    name: kubectl
    state: latest

- name: Ensure old versions of Docker are not installed.
  dnf:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: install the latest stable version of docker-ce
  dnf:
    name: docker-ce
    state: latest

- name: Add {{ user }} user to docker group
  user: name={{ user }}
    groups=docker
    append=yes
  when: test_mode == false

- name: Install Docker Compose {{ docker_compose_ver }}
  shell: curl -L https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  args:
    warn: false

- name: Set Permissions on Docker Compose
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755

- name: Download mikikube {{ minikube_ver }}
  become: yes
  become_user: root
  get_url:
    url: 'https://storage.googleapis.com/minikube/releases/v{{ minikube_ver }}/minikube-linux-amd64'
    dest: '/usr/local/bin/'
    mode: 0755
