---
# Installs containerization Tools

##### Docker #####

- name: Ensure old versions of Docker are not installed
  dnf:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: install the latest stable version of docker-ce
  dnf:
    name: docker-ce
    state: latest

- name: Add {{ user }} user to docker group
  user: name={{ user }}
    groups=docker
    append=yes

- name: Download and install Docker Compose {{ docker_compose_ver }}
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-Linux-x86_64'
    dest: '/usr/local/bin/'
    mode: 0755

##### Kubernetes #####

- name: install the latest version of kubectl
  dnf:
    name: kubectl
    state: latest

- name: Download and install minikube {{ minikube_ver }}
  get_url:
    url: 'https://storage.googleapis.com/minikube/releases/v{{ minikube_ver }}/minikube-linux-amd64'
    dest: '/usr/local/bin/'
    mode: 0775
