---

- name: install the 'Development Tools' package group
  dnf:
    name: '@Development Tools'
    state: present

- name: install the 'Editors' package group
  dnf:
    name: '@Editors'
    state: present

- name: install the 'Cloud Management Tools' package group
  dnf:
    name: '@Cloud Management Tools'
    state: present

#- name: install the latest version of atom
#  dnf:
#    name: atom
#    state: latest

- name: install the latest version of python-pip
  dnf:
    name: python-pip
    state: latest

- name: install the latest version of snap
  dnf:
    name: snap
    state: latest
