---
# Installs web browsers, and system utilities

- name: Add Google Chrome repo
  yum_repository:
    name: google-chrome
    description: google-chrome - $basearch
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/$basearch
    gpgkey: https://dl-ssl.google.com/linux/linux_signing_key.pub
    gpgcheck: yes
    repo_gpgcheck: yes
    enabled: yes
    state: present

##### System Utils #####

- name: install the latest version of htop
  dnf:
    name: htop
    state: latest

##### IRC CLient #####

- name: install the latest version of hexchat
  dnf:
    name: hexchat
    state: latest

##### Torrent Client #####

- name: install the latest version of qbittorrent
  dnf:
    name: qbittorrent
    state: latest

##### Web Browsers #####

- name: install the latest stable version of Google chrome
  dnf:
    name: google-chrome-stable
    state: latest
