---
# Installs compilers web browsers, and system utilities

- name: install the 'Development Tools' package group
  dnf:
    name: '@Development Tools'
    state: present

- name: install the latest version of python-pip
  dnf:
    name: python-pip
    state: latest

##### System Utils #####

- name: install the latest version of CURL
  dnf:
    name: curl
    state: latest

- name: install the latest version of wget
  dnf:
    name: wget
    state: latest

- name: install the latest version of openssh-server
  dnf:
    name: openssh-server
    state: latest

- name: install the latest version of htop
  dnf:
    name: htop
    state: latest

##### Web Browsers #####

- name: install the latest version of chromium
  dnf:
    name: chromium
    state: latest

- name: install the latest stable version of Google chrome
  dnf:
    name: google-chrome-stable
    state: latest

- name: install the latest stable version of firefox
  dnf:
    name: firefox
    state: latest
