---
# Installs web browsers, and system utilities

##### System Utils #####

- name: install the latest version of htop
  dnf:
    name: htop
    state: latest

##### IRC CLient #####

- name: install the latest version of hexchat
  dnf:
    name: hexchat
    state: latest

##### Torrent Client #####

- name: install the latest version of qbittorrent
  dnf:
    name: qbittorrent
    state: latest

##### Web Browsers #####

- name: install the latest stable version of Google chrome
  dnf:
    name: google-chrome-stable
    state: latest
