---
# Installs and configures DNF repositories

  # Requried for Ansible to work with SE-Linux enabled
- name: install the latest version of libselinux-python
  dnf:
    name: libselinux-python
    state: latest

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
