---
# Installs and configures DNF repositories

  # Requried for Ansible to work with SE-Linux enabled
- name: install the latest version of libselinux-python
  dnf:
    name: libselinux-python
    state: latest

- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  async: 1000
  poll: 0
  register: dnf_sleeper_update

# Source: http://docs.ansible.com/ansible/latest/playbooks_async.html
- name: check on initial update
  async_status: jid={{ dnf_sleeper_update.ansible_job_id }}
  register: job_result_update
  until: job_result_update.finished
  retries: "{{ update_retries }}"
